src/App.tsx
src/index.tsx
src/routes/AdminRoutes.tsx
src/routes/AppRoutes.tsx
src/ui/components/molecule/admin/Layout/admin-layout.stories.tsx
src/ui/components/molecule/admin/Layout/admin-layout.tsx
src/ui/components/molecule/admin/slide-menu/slide-menu.stories.tsx
src/ui/components/molecule/admin/slide-menu/slide-menu.tsx
src/ui/pages/page-test.tsx
tsconfig.json

레이아웃부분 스토리북 헤더쪽 CSS가 반영이 안되서 확인해보고싶으면 말해주심 제가 스샷이라도 올림요 그냥 지금 올림요

[Admin] 어드민 레이아웃 구현

---

src/index.css
tailwind.config.js

color, screen break point 작성완료
추후 작업 전부 완료시 머지할께용

Chore: tailwind CSS configuration setting

---

src/hooks/use-html-file-submit.hooks.ts
src/store/admin/check-question-answer-store.ts
src/store/chat-store.ts
src/ui/components/admin/modal/edit-modal.tsx
src/ui/pages/admin/file-list.tsx
src/ui/pages/admin/login.tsx
src/ui/pages/admin/question-check.tsx

- question-check, edit-modal에 사용될 때 필요한 상태를 zustand로 전역상태관리하는 코드를 작성하였습니다.
- 기존 코드에서 물어봤던 내용과 사용간 편의성을 위한 store코드에 대한 설명을 주석 처리 하였습니다.
- edit-modal에 대한 사용확장성 증가를 위한 리팩토링이 필요해보입니다.

[Admin] check question and answer store

---

.storybook/main.ts
.storybook/preview.ts
package-lock.json
package.json
postcss.config.js
src/ui/components/atom/preset/preset-button.tsx

type : children -> any 수정
String으로 바꾸니 오류발생
disabled 추가

[User] Fix: preset-button-component type수정

---

src/api/search-auto-complete.ts
src/hooks/use-auto-complete.hooks.ts
src/hooks/use-debounce.hooks.ts
src/ui/components/atom/auto-complete/auto-complete.tsx
src/ui/components/molecule/user/chat-form/chat-form.tsx
src/ui/pages/admin/login.tsx

자동완성 검색기능 추가하였습니다.
use-debounce 훅 생성하여 불필요하게 api호출을 하는 과정을 줄였습니다.

[USER] auto complete search

---

src/api/admin-generate-question.ts
src/api/admin-retrieve-file.ts
src/routes/admin-routes.tsx
src/ui/components/admin/Layout/admin-layout.tsx
src/ui/components/admin/slide-menu/slide-menu.tsx
src/ui/pages/admin/file-list.tsx
src/ui/pages/admin/generate-question.tsx
src/ui/pages/admin/login.tsx

[Admin] generate-new custom question page

---

src/ui/components/atom/auto-complete/auto-complete.tsx
src/ui/components/atom/chat-card/chat-card.tsx
src/ui/components/atom/text-input/text-input.tsx
src/ui/components/molecule/chat-form/chat-form.tsx
src/ui/components/molecule/header/header.tsx
src/ui/components/molecule/menu-drawer/menu-drawer.tsx
src/ui/pages/maru-egg.tsx

- 데스크탑 뷰 화면 width:390 height:780고정
- chat-form Padding값 줄이기 
- border값 추가 및 색상 변경
- shadow 추가
- 자동완성 부분 색상 변경 및 패딩값 변경
- 기타 폰트 크기 및 색상 조정
- 모바일 화면 시 max-w max-h값 수정 필요
- MenuDraw시 absolute 적용

refactor: 반응형 및 기타 css수정

---

src/ui/components/molecule/menu-drawer/menu-drawer.tsx

- 기존 Drawer Componnet의 모달이 Header의 CSS에 종속되지 않는 문제를 해결하였습니다.
- 입학관련문의 전화번호 가독성이 더 좋도록 수정하였습니다.

Refactor: Drawer Component 모바일 화면에 맞게  반응형 수정

---

src/ui/pages/maru-egg.tsx

fix: css속성 수정

---

src/ui/components/admin/modal/edit-modal.tsx

기존-> 편집하기 클릭시 이전에 있던게 있으면 그 답변 내용이 나옴
지금-> 현재 질문에 맞게 답변 내용 나오도록 설정

refactor: add useEffect for update content

---

src/hooks/use-chat-section.hooks.ts
src/ui/components/molecule/chat-section/chat-section.tsx

- chat-section컴포넌트에 동작부분 훅 추가하였습니다.
- ref사용하여 스크롤 안내려도 자동으로 응답오면 스크롤 오도록 하였습니다.

[USER] use-chat-section hooks and scroll action

---

src/hooks/use-chat-form.hooks.ts
src/ui/components/atom/chat-card/chat-card.tsx
src/ui/components/atom/loader/loader.tsx

Feat: loader component 재오픈

---

src/ui/components/molecule/chat-section/chat-section.tsx
src/ui/components/molecule/header/header.tsx
src/ui/components/molecule/menu-drawer/menu-drawer.tsx
src/ui/pages/maru-egg.tsx
tailwind.config.js

- tailwind.config.js mobile 미적용되는 부분 수정하였습니다.
- min-width , min-height 적용하여 특정 사이즈 이하로 작아지지않도록 적용하였습니다.
- mobile에서는 rounded-none으로 바꾸고 화면에 fit해보여질 수 있도록 적용하였습니다.
- type 부분 특정 부분만 글자 크기 커지는 현상 재발해 items-start통해 고정하였습니다.
- font사이즈가 고정되어있어 반응형에 맞게 바뀌어야할지는 다양한 기기에서 검토해봐야 합니다.

Refactor: 모바일 화면에서의  반응형 적용

---

src/hooks/use-auto-complete.hooks.ts
src/ui/components/atom/auto-complete/auto-complete.tsx

- debounce 1초였는데 너무 길어서 500으로 줄였습니다.
- 자동완성 기능에서 isChecked된 검색만 보이도록 설정했습니다.

[USER] autocomplete refactor

---

src/api/admin-check-question-answer.ts
src/api/admin/admin-check-question-answer.ts
src/api/admin/admin-edit-answer.ts
src/api/admin/admin-generate-question.ts
src/api/admin/admin-llm-file.ts
src/api/admin/admin-login.ts
src/api/admin/admin-question-check.ts
src/api/admin/admin-search-by-id.ts
src/api/admin/question-type-status/change-type-status.ts
src/api/admin/question-type-status/get-type-status.ts
src/hooks/use-chat-form.hooks.ts
src/routes/admin-routes.tsx
src/store/type-disabled-store.ts
src/ui/components/admin/Layout/admin-layout.tsx
src/ui/components/admin/modal/edit-modal.tsx
src/ui/components/admin/slide-menu/slide-menu.tsx
src/ui/components/molecule/chat-section/chat-section.tsx
src/ui/components/molecule/menu-drawer/menu-drawer.tsx
src/ui/pages/admin/file-list.tsx
src/ui/pages/admin/generate-question.tsx
src/ui/pages/admin/login.tsx
src/ui/pages/admin/question-check.tsx
src/ui/pages/admin/type-disabled.tsx
src/ui/pages/maru-egg.tsx

브랜치 이름 잘못적은거 죄송함다,ㅇ,,,
버튼 관리페이지 & 버튼 상태 받아서 페이지에 적용하도록 하였습니다.

[USER&ADMIN] button disabled 

---

src/ui/components/molecule/chat-section/chat-section.tsx
src/ui/components/molecule/header/header.tsx
src/ui/components/molecule/menu-drawer/menu-drawer.tsx

[USER] message api add

---

src/hooks/use-chat-form.hooks.ts
src/hooks/use-chat-section.hooks.ts
src/store/chat-store.ts
src/ui/components/molecule/chat-section/chat-section.tsx
src/ui/components/user-domain/category-preset-buttons.tsx
src/ui/components/user-domain/question-preset-buttons.tsx
src/ui/components/user-domain/type-preset-buttons.tsx

- 출처 나오는 버튼 일단 기능먼저 구현해놨습니다. 
- message관련 위치 일단 통일시켜놨고, 수정이 많이 필요해보이긴합니다. 애매하면 그냥 다른 라이브러리로 구현해봐도 될 것 같습니다.
- 이거 기준으로 그 외 프리셋 작업 해주시면 됩니당

[USER] Feat: reference preset button component

---

src/api/admin/question-manage/admin-check-question-answer.ts
src/api/admin/question-manage/admin-delete-question.ts
src/api/admin/question-manage/admin-edit-answer.ts
src/api/admin/question-manage/admin-edit-question.ts
src/api/admin/question-manage/admin-generate-question.ts
src/api/admin/question-manage/admin-question-check.ts
src/api/admin/question-manage/admin-search-by-id.ts
src/hooks/use-chat-form.hooks.ts
src/store/admin/check-question-answer-store.ts
src/ui/components/admin/modal/edit-modal.tsx
src/ui/pages/admin/generate-question.tsx
src/ui/pages/admin/question-check.tsx

이거 onRow에 onClick이벤트핸들러 걸어놔서,,, 흠,,, 일단 하하,,,

[TSK-39] admin question management

---

src/ui/components/atom/chat-card/chat-card.tsx

- 답변 넘어가는 부분 최대 넓이설정, break-word속성으로 해결하였습니다.

[TSK-47] fix: 답변 출처 링크 넘어가는 버그 해결

---

src/ui/components/atom/text-input/text-input.tsx
src/ui/components/molecule/chat-section/chat-section.tsx

- input태그 textarea로 바꿔서 장문 대처하도록 하였습니다.

refactor: input tag to textarea

---

src/hooks/use-chat-form.hooks.ts
src/hooks/use-textarea-submit.hooks.ts
src/ui/components/molecule/chat-form/chat-form.tsx

- textInput컴포넌트 사용대신 textarea사용하여 장문에 유연하게 대처할 수 있도록 하였습니다.
- enterSubmit hook을 추가하여 enter버튼 누르고도 submit되도록 처리하였습니다.

[Tsk-49] ChatForm enter event issue clear

---

package-lock.json
package.json
src/api/get-admission-detail-type.query.ts
src/hooks/use-chat-section.hooks.ts
src/hooks/use-detail-type-prompt.hooks.ts
src/hooks/use-preset-button.hooks.ts
src/store/type-category-store.ts
src/store/user-detail-type-store.ts
src/ui/components/atom/chat-card/chat-card.tsx
src/ui/components/atom/dropdown/dropdown.stories.tsx
src/ui/components/atom/dropdown/dropdown.tsx
src/ui/components/molecule/chat-section/chat-section.tsx
src/ui/pages/maru-egg.tsx

- atom component 기본 구조
- Storybook 연결
- 아직 진행중입니다.

[TSK-55] add dropdown atom-component

---

public/index.html
src/hooks/use-preset-button.hooks.ts
src/ui/components/molecule/chat-form/chat-form.tsx
src/ui/components/molecule/chat-section/chat-section.tsx
src/ui/components/user-domain/question-preset-buttons.tsx

Tsk 999 hot fix

---

src/hooks/use-preset-button.hooks.ts

- 단순히 세부 전형 이름만 넣는 것이 아닌 대전형 - 소전형 을 같이 넣어주었습니다.

refactor: detail type question add korean type

---

package-lock.json
package.json
src/App.tsx

- 리뷰어가 중점적으로 봐야하는 부분을 바로 알 수 있도록 변경된 내용을 나열합니다.
- UI변동이 있는 경우 스크린샷 혹은 gif파일을 함께 볼 수 있으면 좋을 것 같습니다.
- 해당 작업 간 긴가민가했던 부분, 고민했던 부분이 있으면 적어주세요.
- 해당 부분이 해소되었다면 어떤 방법으로 해결했는지에 대한 방법을 적어주세요.
- 해당 부분에 대한 리뷰어의 생각이 궁금합니다.

chore: add vercel speed insights monitoring tools
